### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by minkiminki** [snu-sf/fairness#64]
- [ ] add yield flags in simulation relation @mori1116 
- [ ] handle states with lenses @damhiya (https://github.com/snu-sf/fairness/tree/state-reasoning)
- [ ] invariant @damhiya (https://github.com/snu-sf/fairness/tree/fancy-update)

### Not urgent
- [ ] reuse IProp in Iris
- [ ] unary logic
