### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mori1116** [snu-sf/fairness#8]
- [x] Prove equivalence of `ord-select` and `ind_select`
- [x] Define `scheduler`
- [x] Prove local adequacy: `scheduler` + `local_sim mod` -> `global sim`
- [x] Decide whether to include `spawn`
- [x] Collect examples
